### PR TITLE
flagged mongodb calls

### PR DESCRIPTION
**Pull request by cfoskin**
Flagged the db calls and Im not sure if this will be changed as it is a layer that sits on top of mongo 

Ping @mikenairn @odra @PhilipGough

### CODE REVIEW

**Comment by odra** [comment]
I think it boils down to where fh-db is being used since it's just a mongodb wrapper/library.

**Comment by cfoskin** [comment]
@odra Agreed

**Comment by odra** [comment]
yep this close this one.

**Comment by mikenairn** [comment]
@cfoskin @odra Agreed. Changes, if any, will be required where this is being used rather in here. I'd say we can close this. Do we have an idea of what uses fh-db?

**Comment by cfoskin** [comment]
@mikenairn I know fh-mbaas-api uses this anyway

**Pull request closed without merging**
