### PR TITLE
Update to exclude replicaSet parameter if empty

### PR DESCRIPTION
**Pull request by luigizuccarelli**
@matzew Please review

Please refer to JIRA RHMAP-9817

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by luigizuccarelli** [comment]
Retest this please

**Comment by luigizuccarelli** [comment]
@philbrookes - please review when you have a chance

**Comment by philbrookes** [comment]
:+1: This look good to me, I can't think of any parameters here that would ever need to be an empty string.

**Comment by luigizuccarelli** [comment]
@philbrookes - Thanks, when we set the envar MONGODB_REPLICA_NAME in the template to empty it sets replicaSet='' and causes this problem

**Pull request merged**
